// app/api/roodber8/ab-press/generate/route.ts
// Accounting Body Press - PDF Generation API
// Fetches course from Sanity, renders PDFs, returns ZIP
/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from "next/server"
import { renderToBuffer } from "@react-pdf/renderer"
import React from "react"
import { BookTemplate } from "@/components/book/BookTemplate"
import { FullCoverTemplate } from "@/components/book/FullCoverTemplate"

// Vercel Pro: allow up to 300s for large book renders (silently ignored on free plan)
export const maxDuration = 300

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID ?? "4rllejq1"
const DATASET    = process.env.NEXT_PUBLIC_SANITY_DATASET    ?? "production"
const BASE_URL   = `https://${PROJECT_ID}.api.sanity.io/v2023-05-03/data/query/${DATASET}`

async function sanityFetch(query: string) {
  const res = await fetch(`${BASE_URL}?query=${encodeURIComponent(query)}`, { cache: "no-store" })
  if (!res.ok) throw new Error(`Sanity fetch failed: ${res.status}`)
  const data = await res.json()
  return data.result
}

async function buildCourse(slug: string) {
  const course = await sanityFetch(`
    *[_type == "course" && slug.current == "${slug}" && (status == "published" || !defined(status))][0] {
      _id, title, slug, description, level,
      "categoryTitle": category->title,
      "chapters": chapters[] {
        _key, chapterTitle, chapterOrder,
        "lessons": lessons[defined(@->._id) && !(@->_id in path("drafts.**"))]-> {
          _id, title, slug, order,
          "linkedArticles": linkedArticles[defined(@->._id) && !(@->_id in path("drafts.**"))]-> {
            _id, title, slug, excerpt, mcqUrl, body
          }
        }
      }
    }
  `)
  if (!course) throw new Error("Course not found")

  const chapters = await Promise.all(
    (course.chapters || []).map(async (chapter: any) => {
      const lessons = await Promise.all(
        (chapter.lessons || []).map(async (lesson: any) => {
          const linkedArticles = await Promise.all(
            (lesson.linkedArticles || []).map(async (article: any) => {
              let quizQuestions: any[] = []
              if (article.mcqUrl) {
                const parts = article.mcqUrl.split("/")
                const practiceSlug = parts[parts.length - 1]
                try {
                  const practicePost = await sanityFetch(`
                    *[_type == "practicePost" && slug.current == "${practiceSlug}" && "accountingbody" in showOnSites][0] {
                      "quizQuestions": quizQuestions[] {
                        questionText, options, correctIndex, explanation, difficulty, timeTargetMinutes
                      }
                    }
                  `)
                  quizQuestions = practicePost?.quizQuestions || []
                } catch {
                  quizQuestions = []
                }
              }
              return { ...article, quizQuestions }
            })
          )
          return { ...lesson, linkedArticles }
        })
      )
      return { ...chapter, lessons }
    })
  )
  return { ...course, chapters }
}

const BOOK_TYPE_LABELS: Record<string, string> = {
  combined: "Study Text and Practice Kit",
  study:    "Study Text",
  practice: "Practice Kit",
}

function buildMetadata(subtitle: string, bookType: string, edition: string, course: any): string {
  const lines = [
    "ACCOUNTING BODY PRESS - BOOK METADATA",
    "=====================================",
    "",
    `Title: ${subtitle}`,
    `Type: ${BOOK_TYPE_LABELS[bookType] || bookType}`,
    `Author: Accounting Body Editorial Team`,
    `Publisher: Accounting Body Press`,
    `Edition: ${edition}`,
    `Year: ${new Date().getFullYear()}`,
    `Language: English`,
    `Trim Size: 6 x 9 inches`,
    `Interior: Black and White`,
    `Paper: White`,
    "",
    "COURSE INFO",
    "-----------",
    `Course: ${course.title}`,
    `Level: ${course.level || "Not specified"}`,
    `Category: ${course.categoryTitle || "Not specified"}`,
    `Chapters: ${(course.chapters || []).length}`,
    "",
    "KDP UPLOAD INSTRUCTIONS",
    "-----------------------",
    "1. Log in to kdp.amazon.com",
    "2. Create new paperback title",
    "3. Enter metadata from above",
    "4. Upload interior.pdf as manuscript",
    "5. Upload cover.pdf as cover",
    "6. Choose 6x9 trim size, black and white interior",
    "7. Set price and territories",
    "8. Submit for review",
    "",
    `Generated: ${new Date().toISOString()}`,
    "Generated by: Accounting Body Press Publishing System",
  ]
  return lines.join("\n")
}

// ── KDP pre-flight checks ────────────────────────────────────────────────────
// Inspects the rendered PDFs and certifies KDP-readiness in the ZIP.
function buildPreflight(interiorPdf: Buffer, coverPdf: Buffer, pageCount: number, subtitle: string, bookType: string): string {
  const interiorStr = interiorPdf.toString("binary")
  const coverStr    = coverPdf.toString("binary")
  const checks: { name: string; pass: boolean; detail: string }[] = []

  // 1. Fonts embedded (TrueType font files present, no standard-font fallback)
  const hasEmbedded   = /\/FontFile2/.test(interiorStr) && /\/FontFile2/.test(coverStr)
  const hasStdHelv    = /\/BaseFont\s*\/Helvetica[^-]/.test(interiorStr) || /\/BaseFont\s*\/Helvetica[^-]/.test(coverStr)
  checks.push({ name: "Fonts embedded", pass: hasEmbedded && !hasStdHelv,
    detail: hasEmbedded && !hasStdHelv ? "Liberation Sans embedded in interior and cover" : "Non-embedded font detected - KDP may reject" })

  // 2. Page count within KDP paperback limits (6x9 black and white: 24-828)
  const pagesOk = pageCount >= 24 && pageCount <= 828
  checks.push({ name: "Page count", pass: pagesOk, detail: pageCount + " pages (KDP limit 24-828)" })

  // 3. Cover dimensions match the spine formula for this page count
  const spineIn   = Math.max(pageCount * 0.002252, 0.5)
  const expectedW = (6.125 * 2 + spineIn) * 72
  const expectedH = 9.25 * 72
  const boxMatch  = coverStr.match(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/)
  const coverW    = boxMatch ? parseFloat(boxMatch[1]) : 0
  const coverH    = boxMatch ? parseFloat(boxMatch[2]) : 0
  const coverOk   = Math.abs(coverW - expectedW) < 1 && Math.abs(coverH - expectedH) < 1
  checks.push({ name: "Cover dimensions", pass: coverOk,
    detail: coverW.toFixed(2) + " x " + coverH.toFixed(2) + " pts (expected " + expectedW.toFixed(2) + " x " + expectedH.toFixed(2) + ", spine " + spineIn.toFixed(3) + "in)" })

  // 4. Interior trim is 6x9
  const trimOk = /\/MediaBox\s*\[\s*0\s+0\s+432\s+648\s*\]/.test(interiorStr)
  checks.push({ name: "Interior trim 6x9", pass: trimOk, detail: trimOk ? "432 x 648 pts confirmed" : "Unexpected interior page size" })

  // 5. Title present
  checks.push({ name: "Title metadata", pass: subtitle.trim().length > 0, detail: subtitle || "MISSING" })

  const allPass = checks.every((c) => c.pass)
  const lines = [
    "ACCOUNTING BODY PRESS - KDP PRE-FLIGHT REPORT",
    "=============================================",
    "",
    "Book: " + subtitle + " (" + bookType + ")",
    "Generated: " + new Date().toISOString(),
    "",
    ...checks.map((c) => (c.pass ? "[PASS] " : "[FAIL] ") + c.name + " - " + c.detail),
    "",
    allPass
      ? "VERDICT: KDP-READY - upload interior.pdf and cover.pdf as-is."
      : "VERDICT: NOT READY - resolve [FAIL] items before uploading to KDP.",
  ]
  return lines.join("\n")
}

// ── ZIP builder (no external dependency) ─────────────────────────────────────
function u32le(n: number): Buffer {
  const b = Buffer.alloc(4); b.writeUInt32LE(n, 0); return b
}
function u16le(n: number): Buffer {
  const b = Buffer.alloc(2); b.writeUInt16LE(n, 0); return b
}
function crc32(buf: Buffer): number {
  const t: number[] = []
  for (let i = 0; i < 256; i++) {
    let c = i
    for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    t[i] = c
  }
  let crc = 0xffffffff
  for (let i = 0; i < buf.length; i++) crc = t[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8)
  return (crc ^ 0xffffffff) >>> 0
}
function buildZip(files: { name: string; data: Buffer }[]): Buffer {
  const locals: Buffer[] = []
  const centrals: Buffer[] = []
  let offset = 0
  for (const f of files) {
    const name = Buffer.from(f.name, "utf8")
    const crc  = crc32(f.data)
    const size = f.data.length
    const local = Buffer.concat([
      Buffer.from([0x50,0x4b,0x03,0x04]),
      u16le(20),u16le(0),u16le(0),u16le(0),u16le(0),
      u32le(crc),u32le(size),u32le(size),
      u16le(name.length),u16le(0),
      name, f.data,
    ])
    locals.push(local)
    centrals.push(Buffer.concat([
      Buffer.from([0x50,0x4b,0x01,0x02]),
      u16le(20),u16le(20),u16le(0),u16le(0),u16le(0),u16le(0),
      u32le(crc),u32le(size),u32le(size),
      u16le(name.length),u16le(0),u16le(0),u16le(0),u16le(0),
      u32le(0),u32le(offset),name,
    ]))
    offset += local.length
  }
  const cd   = Buffer.concat(centrals)
  const eocd = Buffer.concat([
    Buffer.from([0x50,0x4b,0x05,0x06]),
    u16le(0),u16le(0),
    u16le(files.length),u16le(files.length),
    u32le(cd.length),u32le(offset),u16le(0),
  ])
  return Buffer.concat([...locals, cd, eocd])
}

// ── POST handler ─────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { slug, bookType, edition, subtitle } = body
    if (!slug)     return NextResponse.json({ error: "slug is required" },     { status: 400 })
    if (!bookType) return NextResponse.json({ error: "bookType is required" }, { status: 400 })

    const course = await buildCourse(slug)

    // Pass 1: probe render - collect the start page of every chapter
    const pageMap: Record<number, number> = {}
    await renderToBuffer(
      React.createElement(BookTemplate, {
        course,
        bookType: bookType as any,
        edition:  edition  || "2026/27 Edition",
        subtitle: subtitle || course.title,
        onChapterPage: (ci: number, page: number) => { pageMap[ci] = page },
      }) as any
    )

    // Pass 2: final render with TOC page numbers filled in
    const interiorPdf = await renderToBuffer(
      React.createElement(BookTemplate, {
        course,
        bookType: bookType as any,
        edition:  edition  || "2026/27 Edition",
        subtitle: subtitle || course.title,
        pageMap,
      }) as any
    )

    // Count pages from interior PDF for dynamic spine width
    const interiorStr = interiorPdf.toString("binary")
    const pageMatches = interiorStr.match(/\/Type\s*\/Page[^s]/g)
    const pageCount = pageMatches ? pageMatches.length : 300

    // Render full wrap cover (front + spine + back) with dynamic spine
    const coverPdf = await renderToBuffer(
      React.createElement(FullCoverTemplate, {
        subtitle:  subtitle || course.title,
        bookType:  bookType as any,
        edition:   edition  || "2026/27 Edition",
        pageCount,
      }) as any
    )

    const metaBuffer = Buffer.from(
      buildMetadata(subtitle || course.title, bookType, edition || "2026/27 Edition", course),
      "utf8"
    )

    const preflightBuffer = Buffer.from(
      buildPreflight(interiorPdf, coverPdf, pageCount, subtitle || course.title, bookType),
      "utf8"
    )

    const zip      = buildZip([
      { name: "interior.pdf",         data: interiorPdf     },
      { name: "cover.pdf",            data: coverPdf        },
      { name: "metadata.txt",         data: metaBuffer      },
      { name: "preflight-report.txt", data: preflightBuffer },
    ])
    const filename = `${slug}-${bookType}.zip`

    return new NextResponse(new Uint8Array(zip), {
      status: 200,
      headers: {
        "Content-Type":        "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length":      String(zip.length),
      },
    })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Unknown error"
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
