import type { JobProvider } from '@/lib/providers'

/**
 * Minimal, fully-typed JobProvider fixture for tests. Every field the
 * production code actually branches on (field_mapping, adapter_key,
 * source_score, platform_tags, source_name, base_url, etc.) should be
 * overridden per test; everything else here is a neutral placeholder.
 */
export function makeProvider(overrides: Partial<JobProvider> = {}): JobProvider {
  return {
    id: 'provider-1',
    slug: 'test-provider',
    name: 'Test Provider',
    provider_type: 'api',
    adapter_key: 'generic-rest',
    status: 'active',
    priority: 1,
    is_affiliate: false,
    data_ownership: null,
    country_codes: [],
    regions: [],
    platform_tags: [],
    source_score: 1,
    keywords: [],
    category_filter: null,
    base_url: null,
    request_config: {},
    auth_type: 'none',
    auth_config: {},
    field_mapping: {},
    response_path: null,
    pagination_style: null,
    max_pages_per_run: 1,
    fetch_interval_minutes: 60,
    fetch_offset_minutes: 0,
    last_fetched_at: null,
    next_fetch_at: null,
    rate_limit_rpm: null,
    rate_limit_daily: null,
    requests_today: 0,
    retry_after_seconds: null,
    health_status: 'ok',
    consecutive_failures: 0,
    last_success_at: null,
    last_error_at: null,
    last_error_message: null,
    last_error_code: null,
    avg_response_ms: null,
    total_jobs_ingested: 0,
    jobs_last_run: 0,
    jobs_today: 0,
    dedup_rate_last_run: null,
    notes: null,
    source_name: 'test-source',
    commercial_terms: null,
    keyword_cursor: null,
    enforce_relevance: false,
    data_quality_status: null,
    last_relevance_rate: null,
    last_avg_description_length: null,
    data_quality_checked_at: null,
    last_alert_state: null,
    last_alert_sent_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...overrides,
  }
}
