/**
 * article-normaliser.ts
 *
 * Converts any AI-generated or exported article JSON (ChatGPT, DeepSeek,
 * Gemini, Claude, hand-written, WordPress export, etc.) into the exact
 * shape the Supabase `articles` table expects.
 *
 * Same architecture as lib/question-normaliser.ts (S37): a normaliser that
 * is lenient about input shape and field naming, logs every transformation
 * it makes so the admin UI can render a diff report, and defers hard
 * publish-readiness checks to a separate `validateNormalisedArticle` pass.
 *
 * Zero runtime dependencies beyond the standard library — safe to import
 * from Node.js API routes or an edge runtime.
 */

// ── Public types ─────────────────────────────────────────────────────────────

/**
 * Every `articles` table column except the ones never set by the normaliser:
 * id (generated by Supabase), content_id (assigned at publish time),
 * created_at / updated_at (set by the database).
 */
export interface NormalisedArticle {
  title:               string
  slug:                string
  content:             string
  excerpt:             string
  category:            string
  category_title:      string
  exam_body:           string[]
  show_on_sites:        string[]
  featured_image_url:  string
  seo_title:           string
  seo_description:     string
  mcq_url:             string
  read_time:           number
  author_name:         string
  last_reviewed:       string | null
  status:              string
  platform:            string
  canonical_owner:     string
  wp_id:               string
  ai_summary:          string
  ai_key_terms:        string[]
  ai_searchable:       boolean
  eticpa_level:        string
  eticpa_module:       string
  eticpa_topic:        string
  content_type:        string
  difficulty:          string
  published_at:        string | null
}

export interface NormaliseArticleResult {
  article:  NormalisedArticle
  changes:  string[]
  warnings: string[]
}

export interface NormaliseManyArticlesResult {
  articles: NormalisedArticle[]
  changes:  string[][]
  warnings: string[][]
}

// ── Field name lookup tables ────────────────────────────────────────────────
// First entry in every list is the canonical DB column name.

const TITLE_KEYS = [
  'title', 'headline', 'name', 'h1', 'heading', 'article_title', 'post_title',
]

const CONTENT_KEYS = [
  'content', 'body', 'html', 'article_body', 'text',
  'full_text', 'main_content', 'body_html', 'content_html',
]

const EXCERPT_KEYS = [
  'excerpt', 'summary', 'description', 'intro', 'introduction',
  'meta_description', 'short_description', 'abstract', 'lead', 'teaser',
]

const CATEGORY_KEYS = [
  'category', 'topic', 'section', 'subject', 'category_slug',
]

const CATEGORY_TITLE_KEYS = [
  'category_title', 'category_name', 'section_title', 'topic_title',
]

const EXAM_BODY_KEYS = [
  'exam_body', 'qualification', 'qualifications', 'exam', 'exams', 'body', 'bodies',
]

const SHOW_ON_SITES_KEYS = [
  'show_on_sites', 'sites', 'platforms', 'visibility', 'publish_to',
]

const FEATURED_IMAGE_KEYS = [
  'featured_image_url', 'image', 'featured_image', 'thumbnail',
  'cover_image', 'hero_image', 'image_url', 'photo',
]

const SEO_TITLE_KEYS = [
  'seo_title', 'meta_title', 'og_title', 'search_title',
]

const SEO_DESCRIPTION_KEYS = [
  'seo_description', 'meta_description', 'og_description', 'search_description',
]

const READ_TIME_KEYS = [
  'read_time', 'reading_time', 'read_minutes', 'minutes', 'time_to_read',
]

const AUTHOR_KEYS = [
  'author_name', 'author', 'by', 'written_by', 'byline',
]

const STATUS_KEYS = [
  'status', 'published', 'is_published',
]

// 'level' is ambiguous with eticpa_level — excluded here when exam_body is eticpa
const DIFFICULTY_KEYS = [
  'difficulty', 'level',
]

const CONTENT_TYPE_KEYS = [
  'content_type', 'type', 'article_type', 'format',
]

const AI_KEY_TERMS_KEYS = [
  'ai_key_terms', 'key_terms', 'keywords', 'tags',
]

// 'level' is ambiguous with difficulty — only consumed here when exam_body is eticpa
const ETICPA_LEVEL_KEYS = [
  'eticpa_level', 'level',
]

const ETICPA_MODULE_KEYS = [
  'eticpa_module', 'module',
]

// 'topic' is ambiguous with category — only consumed here when exam_body is eticpa
const ETICPA_TOPIC_KEYS = [
  'eticpa_topic', 'topic',
]

const PUBLISHED_AT_KEYS = [
  'published_at', 'publishedAt', 'publish_date', 'date',
]

const LAST_REVIEWED_KEYS = [
  'last_reviewed', 'lastReviewed', 'reviewed_at',
]

const STATUS_VALUES = ['published', 'draft', 'archived']

// ── Known category slugs ────────────────────────────────────────────────────

interface CategoryDef { slug: string; title: string; variants: string[] }

const CATEGORY_DEFS: CategoryDef[] = [
  { slug: 'financial-accounting',  title: 'Financial Accounting',  variants: ['financial accounting', 'fa'] },
  { slug: 'management-accounting', title: 'Management Accounting', variants: ['management accounting', 'ma'] },
  { slug: 'financial-management',  title: 'Financial Management',  variants: ['financial management', 'fm'] },
  { slug: 'audit-assurance',       title: 'Audit and Assurance',   variants: ['audit and assurance', 'audit & assurance', 'aa', 'audit'] },
  { slug: 'taxation',              title: 'Taxation',              variants: ['tax', 'taxation', 'tx'] },
  { slug: 'business-management',   title: 'Business Management',   variants: ['business management', 'bm'] },
  { slug: 'economics',             title: 'Economics',             variants: ['economics', 'eco'] },
  { slug: 'financial-market',      title: 'Financial Market',      variants: ['financial market', 'financial markets'] },
  { slug: 'cryptocurrency',        title: 'Cryptocurrency',        variants: ['cryptocurrency', 'crypto'] },
  { slug: 'tools-templates',       title: 'Tools and Templates',   variants: ['tools and templates', 'tools & templates', 'tools'] },
]

/** Normalise a label into a lookup key: lowercase, non-alphanumeric collapsed to single spaces */
function normKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

function buildCategoryLookup(): Map<string, CategoryDef> {
  const map = new Map<string, CategoryDef>()
  for (const def of CATEGORY_DEFS) {
    for (const key of [def.slug, def.title, ...def.variants]) {
      map.set(normKey(key), def)
    }
  }
  return map
}

const CATEGORY_LOOKUP = buildCategoryLookup()

function matchCategory(raw: string): CategoryDef | null {
  return CATEGORY_LOOKUP.get(normKey(raw)) ?? null
}

// ── Generic utility helpers ─────────────────────────────────────────────────

/** Find the first present key from a candidate list, returning which key matched */
function pickWithKey(obj: Record<string, unknown>, keys: string[]): { key: string; value: unknown } | null {
  for (const k of keys) {
    if (k in obj && obj[k] !== null && obj[k] !== undefined) return { key: k, value: obj[k] }
  }
  return null
}

/** Coerce any value to a trimmed non-empty string, or null */
function str(v: unknown): string | null {
  if (v === null || v === undefined) return null
  const s = String(v).trim()
  return s.length > 0 ? s : null
}

/** Generate a url-safe slug: lowercase, non-alphanumeric → hyphen, collapsed, capped at maxLen */
function slugify(input: string, maxLen: number): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
}

/** Lowercase code-style slug for exam_body / show_on_sites values ("ETICPA / ATQ" → "eticpa-atq") */
function slugifyCode(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Strip HTML tags and decode the small set of entities the codebase's own content ever contains */
function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
}

/** Truncate text at the last whitespace boundary before maxLen, appending an ellipsis */
function truncateAtWordBoundary(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text
  const truncated = text.slice(0, maxLen).replace(/\s+\S*$/, '')
  return (truncated || text.slice(0, maxLen)) + '...'
}

/**
 * Extract a plain string field, logging a remap change if the matched key
 * differs from the canonical DB column name.
 */
function extractField(
  obj: Record<string, unknown>,
  keys: string[],
  canonicalName: string,
  changes: string[],
): string | null {
  const hit = pickWithKey(obj, keys)
  if (!hit) return null
  const value = str(hit.value)
  if (value !== null && hit.key !== canonicalName) {
    changes.push(`Remapped '${hit.key}' → ${canonicalName}`)
  }
  return value
}

// ── Field-specific resolvers ────────────────────────────────────────────────

function resolveExamBody(o: Record<string, unknown>, changes: string[], warnings: string[]): string[] {
  const hit = pickWithKey(o, EXAM_BODY_KEYS)
  let items: string[] = []

  if (hit) {
    if (Array.isArray(hit.value)) {
      items = hit.value.map(v => str(v)).filter((v): v is string => v !== null)
    } else {
      // Note: comma/semicolon only — a slash is part of a single qualification
      // name (e.g. "ETICPA / ATQ"), not a delimiter between multiple ones.
      const s = str(hit.value)
      items = s ? s.split(/[,;]/).map(p => p.trim()).filter(Boolean) : []
    }
  }

  if (items.length === 0) {
    warnings.push('No exam_body/qualification found — stored as empty array')
    return []
  }

  const normalised = items.map(slugifyCode).filter(Boolean)
  const deduped = Array.from(new Set(normalised))

  const changed = deduped.length !== items.length || items.some((v, i) => v !== deduped[i])
  if (changed) {
    const original = items.length === 1 ? `'${items[0]}'` : JSON.stringify(items)
    changes.push(`Normalised exam_body from ${items.length === 1 ? 'string' : 'array'} ${original} to [${deduped.map(d => `'${d}'`).join(', ')}]`)
  } else if (hit && hit.key !== 'exam_body') {
    changes.push(`Remapped '${hit.key}' → exam_body`)
  }

  return deduped
}

function resolveShowOnSites(o: Record<string, unknown>, changes: string[]): string[] {
  const hit = pickWithKey(o, SHOW_ON_SITES_KEYS)

  if (!hit) {
    changes.push("Defaulted show_on_sites to ['ab']")
    return ['ab']
  }

  let items: string[]
  if (Array.isArray(hit.value)) {
    items = hit.value.map(v => str(v)).filter((v): v is string => v !== null)
  } else {
    const s = str(hit.value)
    items = s ? s.split(/[,;]/).map(p => p.trim()).filter(Boolean) : []
  }

  if (items.length === 0) {
    changes.push("Defaulted show_on_sites to ['ab']")
    return ['ab']
  }

  const normalised = Array.from(new Set(items.map(slugifyCode).filter(Boolean)))
  if (hit.key !== 'show_on_sites') {
    changes.push(`Remapped '${hit.key}' → show_on_sites`)
  }
  return normalised.length > 0 ? normalised : ['ab']
}

function resolveStatus(o: Record<string, unknown>, changes: string[], warnings: string[]): string {
  const hit = pickWithKey(o, STATUS_KEYS)

  if (!hit) {
    changes.push("Defaulted status to 'published' (not provided)")
    return 'published'
  }

  if (typeof hit.value === 'boolean') {
    const result = hit.value ? 'published' : 'draft'
    changes.push(`Converted boolean '${hit.key}' (${hit.value}) → status '${result}'`)
    return result
  }

  const s = str(hit.value)?.toLowerCase() ?? ''
  if (STATUS_VALUES.includes(s)) {
    if (hit.key !== 'status') changes.push(`Remapped '${hit.key}' → status`)
    return s
  }

  warnings.push(`status '${str(hit.value) ?? String(hit.value)}' did not match any known status ('published', 'draft', 'archived') — defaulted to 'published'`)
  return 'published'
}

function resolveCategory(
  o: Record<string, unknown>,
  isEticpa: boolean,
  changes: string[],
  warnings: string[],
): { category: string; category_title: string } {
  // 'topic' is reserved for eticpa_topic when the article is an ETICPA article
  const categoryKeys = isEticpa ? CATEGORY_KEYS.filter(k => k !== 'topic') : CATEGORY_KEYS
  const hit = pickWithKey(o, categoryKeys)
  const titleHit = pickWithKey(o, CATEGORY_TITLE_KEYS)
  const explicitTitle = titleHit ? str(titleHit.value) : null

  if (!hit) {
    return { category: '', category_title: explicitTitle ?? '' }
  }

  const rawValue = str(hit.value)
  if (!rawValue) {
    return { category: '', category_title: explicitTitle ?? '' }
  }

  if (hit.key !== 'category') {
    changes.push(`Remapped '${hit.key}' → category`)
  }

  const matched = matchCategory(rawValue)

  if (matched) {
    if (normKey(rawValue) !== matched.slug) {
      changes.push(`Normalised category '${rawValue}' → '${matched.slug}'`)
    }
    if (explicitTitle) {
      if (titleHit && titleHit.key !== 'category_title') changes.push(`Remapped '${titleHit.key}' → category_title`)
      return { category: matched.slug, category_title: explicitTitle }
    }
    changes.push(`Generated category_title '${matched.title}' from category`)
    return { category: matched.slug, category_title: matched.title }
  }

  warnings.push(`category '${rawValue}' did not match any known category slug — stored as-is`)
  const sanitised = slugify(rawValue, 200)
  if (explicitTitle) {
    if (titleHit && titleHit.key !== 'category_title') changes.push(`Remapped '${titleHit.key}' → category_title`)
    return { category: sanitised, category_title: explicitTitle }
  }
  return { category: sanitised, category_title: rawValue }
}

function resolveReadTime(
  o: Record<string, unknown>,
  content: string,
  changes: string[],
  warnings: string[],
): number {
  const hit = pickWithKey(o, READ_TIME_KEYS)

  if (hit) {
    const s = str(hit.value)
    const match = s ? s.match(/\d+/) : null
    if (match) {
      const n = parseInt(match[0], 10)
      if (Number.isFinite(n) && n > 0) {
        if (hit.key !== 'read_time') changes.push(`Remapped '${hit.key}' → read_time`)
        return n
      }
    }
    warnings.push(`read_time value '${String(hit.value)}' could not be parsed as a number — estimated from word count instead`)
  }

  const wordCount = stripHtml(content).split(/\s+/).filter(Boolean).length
  const estimated = Math.max(1, Math.ceil(wordCount / 200))
  changes.push(`Estimated read_time as ${estimated} min from word count (${wordCount} words)`)
  return estimated
}

function resolveSeoTitle(o: Record<string, unknown>, title: string, changes: string[]): string {
  const hit = pickWithKey(o, SEO_TITLE_KEYS)
  const raw = hit ? str(hit.value) : null

  if (raw) {
    if (hit && hit.key !== 'seo_title') changes.push(`Remapped '${hit.key}' → seo_title`)
    if (raw.length > 60) {
      changes.push('Trimmed seo_title to 60 chars')
      return truncateAtWordBoundary(raw, 60)
    }
    return raw
  }

  changes.push(title.length > 60
    ? 'Generated seo_title from title (trimmed to 60 chars)'
    : 'Generated seo_title from title')
  return truncateAtWordBoundary(title, 60)
}

function resolveSeoDescription(
  o: Record<string, unknown>,
  excerpt: string,
  content: string,
  changes: string[],
  warnings: string[],
): string {
  const hit = pickWithKey(o, SEO_DESCRIPTION_KEYS)
  const raw = hit ? str(hit.value) : null

  if (raw) {
    if (hit && hit.key !== 'seo_description') changes.push(`Remapped '${hit.key}' → seo_description`)
    if (raw.length > 160) {
      changes.push('Trimmed seo_description to 160 chars')
      return truncateAtWordBoundary(raw, 160)
    }
    return raw
  }

  if (excerpt) {
    changes.push(excerpt.length > 160
      ? 'Generated seo_description from excerpt (trimmed to 160 chars)'
      : 'Generated seo_description from excerpt')
    return truncateAtWordBoundary(excerpt, 160)
  }

  warnings.push('No excerpt found — seo_description generated from content')
  changes.push('Generated seo_description from content (trimmed to 160 chars)')
  return truncateAtWordBoundary(stripHtml(content), 160)
}

function resolveAiKeyTerms(o: Record<string, unknown>, changes: string[]): string[] {
  const hit = pickWithKey(o, AI_KEY_TERMS_KEYS)
  if (!hit) return []

  let items: string[]
  if (Array.isArray(hit.value)) {
    items = hit.value.map(v => str(v)).filter((v): v is string => v !== null)
  } else {
    const s = str(hit.value)
    items = s ? s.split(',').map(p => p.trim()).filter(Boolean) : []
    if (items.length > 1) changes.push(`Split comma-separated '${hit.key}' into ai_key_terms array`)
  }

  const deduped = Array.from(new Set(items))
  if (hit.key !== 'ai_key_terms' && deduped.length > 0 && items.length <= 1) {
    changes.push(`Remapped '${hit.key}' → ai_key_terms`)
  }
  return deduped
}

function resolveAiSearchable(o: Record<string, unknown>, changes: string[]): boolean {
  if (typeof o.ai_searchable === 'boolean') return o.ai_searchable
  changes.push('Defaulted ai_searchable to true')
  return true
}

function resolveDate(
  o: Record<string, unknown>,
  keys: string[],
  canonicalName: string,
  changes: string[],
  warnings: string[],
): string | null {
  const hit = pickWithKey(o, keys)
  if (!hit) return null

  const s = str(hit.value)
  if (!s) return null

  const d = new Date(s)
  if (Number.isNaN(d.getTime())) {
    warnings.push(`${canonicalName} value '${s}' could not be parsed as a date — left unset`)
    return null
  }

  if (hit.key !== canonicalName) changes.push(`Remapped '${hit.key}' → ${canonicalName}`)
  return d.toISOString()
}

function withDefault(
  value: string | null,
  fallback: string,
  fieldName: string,
  changes: string[],
): string {
  if (value !== null) return value
  changes.push(`Defaulted ${fieldName} to '${fallback}'`)
  return fallback
}

function resolveSlug(
  o: Record<string, unknown>,
  title: string,
  changes: string[],
): string {
  const hit = pickWithKey(o, ['slug'])

  if (hit) {
    const raw = str(hit.value)
    if (raw) {
      const sanitised = slugify(raw, 200)
      if (sanitised) {
        if (sanitised !== raw) changes.push(`Sanitised slug '${raw}' → '${sanitised}'`)
        return sanitised
      }
    }
  }

  const base = title || 'untitled-article'
  const generated = slugify(base, 200) || 'untitled-article'
  changes.push(title ? 'Generated slug from title' : 'Generated fallback slug (no title present)')
  return generated
}

// ── Core builder ─────────────────────────────────────────────────────────────

function buildNormalisedArticle(
  raw: Record<string, unknown>,
  seedChanges: string[],
): { article: NormalisedArticle; changes: string[]; warnings: string[] } {
  const changes: string[] = [...seedChanges]
  const warnings: string[] = []

  // ── Title ──
  const titleHit = pickWithKey(raw, TITLE_KEYS)
  const titleValue = titleHit ? str(titleHit.value) : null
  if (titleValue && titleHit && titleHit.key !== 'title') {
    changes.push(`Remapped '${titleHit.key}' → title`)
  }
  if (!titleValue) warnings.push('No title found — title is empty')
  const title = titleValue ?? ''

  // ── Content ──
  const contentHit = pickWithKey(raw, CONTENT_KEYS)
  const contentValue = contentHit ? str(contentHit.value) : null
  if (contentValue && contentHit && contentHit.key !== 'content') {
    changes.push(`Remapped '${contentHit.key}' → content`)
  }
  if (!contentValue) {
    warnings.push('No content found — content is empty')
  } else if (!/<[a-z][\s\S]*>/i.test(contentValue)) {
    warnings.push('content appears to be plain text, not HTML — it will render as-is')
  }
  const content = contentValue ?? ''

  // ── Slug ──
  const slug = resolveSlug(raw, title, changes)

  // ── exam_body must be resolved before category/difficulty/eticpa fields ──
  const exam_body = resolveExamBody(raw, changes, warnings)
  const isEticpa = exam_body.some(e => e.startsWith('eticpa'))

  // ── Category ──
  const { category, category_title } = resolveCategory(raw, isEticpa, changes, warnings)

  // ── Excerpt ──
  const excerpt = extractField(raw, EXCERPT_KEYS, 'excerpt', changes) ?? ''

  // ── show_on_sites ──
  const show_on_sites = resolveShowOnSites(raw, changes)

  // ── Media / SEO ──
  const featured_image_url = extractField(raw, FEATURED_IMAGE_KEYS, 'featured_image_url', changes) ?? ''
  const seo_title = resolveSeoTitle(raw, title, changes)
  const seo_description = resolveSeoDescription(raw, excerpt, content, changes, warnings)

  const mcq_url = extractField(raw, ['mcq_url'], 'mcq_url', changes) ?? ''

  // ── Read time ──
  const read_time = resolveReadTime(raw, content, changes, warnings)

  // ── Author / status ──
  const authorValue = extractField(raw, AUTHOR_KEYS, 'author_name', changes)
  const author_name = withDefault(authorValue, 'Accounting Body Editorial Team', 'author_name', changes)
  const status = resolveStatus(raw, changes, warnings)

  // ── Dates ──
  const last_reviewed = resolveDate(raw, LAST_REVIEWED_KEYS, 'last_reviewed', changes, warnings)
  const published_at = resolveDate(raw, PUBLISHED_AT_KEYS, 'published_at', changes, warnings)

  // ── Platform / canonical owner ──
  const platformValue = extractField(raw, ['platform'], 'platform', changes)
  const platform = withDefault(platformValue, 'ab', 'platform', changes)
  const canonicalOwnerValue = extractField(raw, ['canonical_owner'], 'canonical_owner', changes)
  const canonical_owner = withDefault(canonicalOwnerValue, 'accountingbody', 'canonical_owner', changes)

  const wp_id = extractField(raw, ['wp_id', 'wordpress_id'], 'wp_id', changes) ?? ''

  // ── AI metadata ──
  const ai_summary = extractField(raw, ['ai_summary'], 'ai_summary', changes) ?? ''
  const ai_key_terms = resolveAiKeyTerms(raw, changes)
  const ai_searchable = resolveAiSearchable(raw, changes)

  // ── ETICPA fields (only consume the ambiguous 'level'/'topic' keys when this is an ETICPA article) ──
  const eticpaLevelKeys = isEticpa ? ETICPA_LEVEL_KEYS : ['eticpa_level']
  const eticpaTopicKeys = isEticpa ? ETICPA_TOPIC_KEYS : ['eticpa_topic']
  const eticpa_level  = extractField(raw, eticpaLevelKeys, 'eticpa_level', changes) ?? ''
  const eticpa_module = extractField(raw, ETICPA_MODULE_KEYS, 'eticpa_module', changes) ?? ''
  const eticpa_topic  = extractField(raw, eticpaTopicKeys, 'eticpa_topic', changes) ?? ''

  // ── Type / difficulty ('level' is reserved for eticpa_level on ETICPA articles) ──
  const difficultyKeys = isEticpa ? ['difficulty'] : DIFFICULTY_KEYS
  const difficulty = extractField(raw, difficultyKeys, 'difficulty', changes) ?? ''
  const content_type = extractField(raw, CONTENT_TYPE_KEYS, 'content_type', changes) ?? ''

  const article: NormalisedArticle = {
    title,
    slug,
    content,
    excerpt,
    category,
    category_title,
    exam_body,
    show_on_sites,
    featured_image_url,
    seo_title,
    seo_description,
    mcq_url,
    read_time,
    author_name,
    last_reviewed,
    status,
    platform,
    canonical_owner,
    wp_id,
    ai_summary,
    ai_key_terms,
    ai_searchable,
    eticpa_level,
    eticpa_module,
    eticpa_topic,
    content_type,
    difficulty,
    published_at,
  }

  return { article, changes, warnings }
}

// ── JSON parsing ─────────────────────────────────────────────────────────────

/** Strip markdown code fences and parse JSON, tolerating surrounding prose */
function parseJsonInput(rawJson: string): { parsed: unknown; changes: string[] } {
  const changes: string[] = []
  const trimmed = rawJson.trim()
  const fenceStripped = trimmed
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim()

  try {
    const parsed = JSON.parse(fenceStripped)
    if (fenceStripped !== trimmed) changes.push('Stripped markdown code fences from JSON input')
    return { parsed, changes }
  } catch {
    // Fall through to extraction from surrounding text
  }

  const objStart = fenceStripped.indexOf('{')
  const objEnd = fenceStripped.lastIndexOf('}')
  const arrStart = fenceStripped.indexOf('[')
  const arrEnd = fenceStripped.lastIndexOf(']')
  const objCandidate = objStart >= 0 && objEnd > objStart ? fenceStripped.slice(objStart, objEnd + 1) : null
  const arrCandidate = arrStart >= 0 && arrEnd > arrStart ? fenceStripped.slice(arrStart, arrEnd + 1) : null
  const candidate = objCandidate && (!arrCandidate || objStart < arrStart) ? objCandidate : arrCandidate

  if (!candidate) {
    throw new Error('Input is not valid JSON. Please paste a valid JSON object or array.')
  }

  try {
    const parsed = JSON.parse(candidate)
    changes.push('Extracted JSON from surrounding text')
    return { parsed, changes }
  } catch (err: unknown) {
    const detail = err instanceof Error ? err.message : String(err)
    throw new Error(`Input is not valid JSON: ${detail}`)
  }
}

/** True if the object looks like it carries article-shaped data */
function looksLikeArticle(o: Record<string, unknown>): boolean {
  return pickWithKey(o, TITLE_KEYS) !== null || pickWithKey(o, CONTENT_KEYS) !== null
}

/** Resolve any top-level shape down to a flat array of raw article objects */
function extractArticleObjects(parsed: unknown): Record<string, unknown>[] {
  if (Array.isArray(parsed)) {
    return parsed.filter((v): v is Record<string, unknown> => typeof v === 'object' && v !== null)
  }

  if (typeof parsed === 'object' && parsed !== null) {
    const o = parsed as Record<string, unknown>

    if (Array.isArray(o.articles)) {
      return o.articles.filter((v): v is Record<string, unknown> => typeof v === 'object' && v !== null)
    }

    if (typeof o.article === 'object' && o.article !== null) {
      return [o.article as Record<string, unknown>]
    }

    if (typeof o.data === 'object' && o.data !== null) {
      if (Array.isArray(o.data)) {
        return o.data.filter((v): v is Record<string, unknown> => typeof v === 'object' && v !== null)
      }
      const d = o.data as Record<string, unknown>
      if (Array.isArray(d.articles)) {
        return d.articles.filter((v): v is Record<string, unknown> => typeof v === 'object' && v !== null)
      }
      return [d]
    }

    if (looksLikeArticle(o)) return [o]

    return [o]
  }

  return []
}

// ── Public API ───────────────────────────────────────────────────────────────

/**
 * Normalise a single article from raw JSON (string, markdown-fenced JSON, or
 * JSON embedded in surrounding text). Throws if the input resolves to more
 * than one article — use `normaliseManyArticles` for bulk import.
 */
export function normaliseArticle(rawJson: string): NormaliseArticleResult {
  const { parsed, changes: parseChanges } = parseJsonInput(rawJson)
  const objects = extractArticleObjects(parsed)

  if (objects.length === 0) {
    throw new Error('No article object found in the JSON.')
  }
  if (objects.length > 1) {
    throw new Error(`Found ${objects.length} articles in the JSON — use normaliseManyArticles() for bulk import.`)
  }

  const { article, changes, warnings } = buildNormalisedArticle(objects[0], parseChanges)
  return { article, changes, warnings }
}

/**
 * Normalise every article found in raw JSON (an array, a wrapped
 * `{ articles: [...] }` object, or a single article) into a list.
 */
export function normaliseManyArticles(rawJson: string): NormaliseManyArticlesResult {
  const { parsed, changes: parseChanges } = parseJsonInput(rawJson)
  const objects = extractArticleObjects(parsed)

  if (objects.length === 0) {
    throw new Error('No articles found in the JSON.')
  }

  const articles: NormalisedArticle[] = []
  const changes: string[][] = []
  const warnings: string[][] = []

  for (const raw of objects) {
    const result = buildNormalisedArticle(raw, parseChanges)
    articles.push(result.article)
    changes.push(result.changes)
    warnings.push(result.warnings)
  }

  return { articles, changes, warnings }
}

/**
 * Validate a normalised article for publish-readiness.
 * Returns an empty array when the article is ready to publish.
 */
export function validateNormalisedArticle(article: NormalisedArticle): string[] {
  const errors: string[] = []

  if (typeof article.title !== 'string' || article.title.trim().length === 0) {
    errors.push('title is required')
  }

  if (typeof article.slug !== 'string' || article.slug.trim().length === 0) {
    errors.push('slug is required')
  } else if (!/^[a-z0-9-]+$/.test(article.slug)) {
    errors.push("slug must match /^[a-z0-9-]+$/ (lowercase letters, digits, hyphens only)")
  }

  if (typeof article.content !== 'string' || article.content.trim().length === 0) {
    errors.push('content is required')
  }

  if (!STATUS_VALUES.includes(article.status)) {
    errors.push(`status must be one of: ${STATUS_VALUES.join(', ')}`)
  }

  if (!Array.isArray(article.show_on_sites) || article.show_on_sites.length === 0) {
    errors.push('show_on_sites must be a non-empty array')
  }

  if (Array.isArray(article.exam_body)) {
    const notLowercase = article.exam_body.filter(v => v !== v.toLowerCase())
    if (notLowercase.length > 0) {
      errors.push(`exam_body items must be lowercase (found: ${notLowercase.join(', ')})`)
    }
  }

  return errors
}
