// app/api/roodber8/ab-press/generate-pq/route.ts
// Accounting Body Press - Practice & Revision Kit Generation API
// Route for "practice" book type, using PracticeKitTemplate instead of the
// chapter-by-chapter orchestration used for combined/study books.
//
// TOC page numbers come from a two-pass render:
//   Pass 1 (probe): PracticeKitTemplate with probeOnly=true renders only
//     structural spacers sized from content length — no question/answer
//     text is laid out — and reports the real page number of every
//     chapter, lesson, and the answers section via onSectionPage(). This
//     is fast because react-pdf never has to shape or wrap any text.
//   Pass 2 (final): the full visual render, using the probe's page
//     numbers to fill in the TOC.
// A naive two-pass render (full content laid out twice) previously blew
// the 300s serverless limit on large courses (3,939+ questions). Probing
// with spacers instead of real text keeps pass 1 to a few hundred fixed-
// height boxes, so the combined two passes still fit comfortably.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from "next/server"
import { renderToBuffer } from "@react-pdf/renderer"
import React from "react"
import { PracticeKitTemplate } from "@/components/book/PracticeKitTemplate"
import { FullCoverTemplate } from "@/components/book/FullCoverTemplate"
import { buildCourse, createSupabaseClient } from "@/lib/ab-press-builder"

export const maxDuration = 300

function buildMetadata(subtitle: string, edition: string, course: any): string {
  const lines = [
    "ACCOUNTING BODY PRESS - BOOK METADATA",
    "=====================================",
    "",
    `Title: ${subtitle}`,
    `Type: Practice Kit`,
    `Author: Accounting Body Editorial Team`,
    `Publisher: Accounting Body Press`,
    `Edition: ${edition}`,
    `Year: ${new Date().getFullYear()}`,
    `Language: English`,
    `Trim Size: 6 x 9 inches`,
    `Interior: Black and White`,
    `Paper: White`,
    "",
    "COURSE INFO",
    "-----------",
    `Course: ${course.title}`,
    `Level: ${course.level || "Not specified"}`,
    `Category: ${course.categoryTitle || "Not specified"}`,
    `Chapters: ${(course.chapters || []).length}`,
    "",
    "KDP UPLOAD INSTRUCTIONS",
    "-----------------------",
    "1. Log in to kdp.amazon.com",
    "2. Create new paperback title",
    "3. Enter metadata from above",
    "4. Upload interior.pdf as manuscript",
    "5. Upload cover.pdf as cover",
    "6. Choose 6x9 trim size, black and white interior",
    "7. Set price and territories",
    "8. Submit for review",
    "",
    `Generated: ${new Date().toISOString()}`,
    "Generated by: Accounting Body Press Publishing System",
  ]
  return lines.join("\n")
}

function buildFidelity(course: any, stats: { mcqFailed: string[]; mcqNotFound: string[] }): string {
  const chapters = course.chapters || []
  let lessons = 0, articles = 0, questions = 0, mcqLinks = 0
  let articlesWithWebElements = 0, webElementsRemoved = 0
  for (const ch of chapters) {
    for (const ls of (ch.lessons || [])) {
      lessons++
      for (const art of (ls.linkedArticles || [])) {
        articles++
        if (art.mcqUrl) mcqLinks++
        questions += (art.quizQuestions || []).length
        const pubWarnings: string[] = (art.publicationWarnings || []).filter((w: string) => !w.startsWith("Total:"))
        if (pubWarnings.length > 0) { articlesWithWebElements++; webElementsRemoved += pubWarnings.length }
      }
    }
  }
  // Practice Kit prints questions only - an empty study-note body on a linked
  // article is not a defect for this book type, so it is not tracked here
  // (unlike generate/route.ts's buildFidelity, which reports it).
  const issues = stats.mcqFailed.length + stats.mcqNotFound.length
  const lines = [
    "CONTENT FIDELITY AUDIT",
    "======================",
    "",
    "Source inventory (fetched from Supabase):",
    "  Chapters: " + chapters.length,
    "  Lessons: " + lessons,
    "  Articles: " + articles,
    "  Articles with practice links (mcq_url): " + mcqLinks,
    "  Quiz questions fetched: " + questions,
    "",
  ]
  if (questions === 0) {
    lines.push("[WARN] No quiz questions found for this course - Practice Kit will be empty")
  } else {
    lines.push("[PASS] " + questions + " quiz question(s) found")
  }
  if (stats.mcqNotFound.length > 0) {
    lines.push("[WARN] " + stats.mcqNotFound.length + " linked practice set(s) not found: " + stats.mcqNotFound.join(", "))
  } else {
    lines.push("[PASS] All linked practice sets found")
  }
  if (stats.mcqFailed.length > 0) {
    lines.push("[WARN] " + stats.mcqFailed.length + " practice fetch(es) errored: " + stats.mcqFailed.join(", "))
  } else {
    lines.push("[PASS] No practice fetch errors")
  }
  lines.push("")
  lines.push("PUBLICATION FILTER (web-only elements removed before print)")
  lines.push("-------------------------------------------------------------")
  lines.push("  Articles with web elements removed: " + articlesWithWebElements + " of " + articles)
  lines.push("  Total web elements removed: " + webElementsRemoved)
  lines.push("")
  lines.push(issues === 0
    ? "FIDELITY VERDICT: COMPLETE - every practice set fetched from Supabase is accounted for in this book."
    : "FIDELITY VERDICT: " + issues + " item(s) need review - see [WARN] lines above.")
  return lines.join("\n")
}

function buildPreflight(interiorPdf: Buffer, coverPdf: Buffer, pageCount: number, subtitle: string): string {
  const interiorStr = interiorPdf.toString("binary")
  const coverStr    = coverPdf.toString("binary")
  const checks: { name: string; pass: boolean; detail: string }[] = []
  const hasEmbedded = /\/FontFile2/.test(interiorStr) && /\/FontFile2/.test(coverStr)
  const hasStdHelv  = /\/BaseFont\s*\/Helvetica[^-]/.test(interiorStr) || /\/BaseFont\s*\/Helvetica[^-]/.test(coverStr)
  checks.push({ name: "Fonts embedded", pass: hasEmbedded && !hasStdHelv,
    detail: hasEmbedded && !hasStdHelv ? "Liberation Sans embedded in interior and cover" : "Non-embedded font detected - KDP may reject" })
  const pagesOk = pageCount >= 24 && pageCount <= 828
  checks.push({ name: "Page count", pass: pagesOk, detail: pageCount + " pages (KDP limit 24-828)" })
  const spineIn   = Math.max(pageCount * 0.002252, 0.5)
  const expectedW = (6.125 * 2 + spineIn) * 72
  const expectedH = 9.25 * 72
  const boxMatch  = coverStr.match(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/)
  const coverW    = boxMatch ? parseFloat(boxMatch[1]) : 0
  const coverH    = boxMatch ? parseFloat(boxMatch[2]) : 0
  const coverOk   = Math.abs(coverW - expectedW) < 1 && Math.abs(coverH - expectedH) < 1
  checks.push({ name: "Cover dimensions", pass: coverOk,
    detail: coverW.toFixed(2) + " x " + coverH.toFixed(2) + " pts (expected " + expectedW.toFixed(2) + " x " + expectedH.toFixed(2) + ", spine " + spineIn.toFixed(3) + "in)" })
  const trimOk = /\/MediaBox\s*\[\s*0\s+0\s+432\s+648\s*\]/.test(interiorStr)
  checks.push({ name: "Interior trim 6x9", pass: trimOk, detail: trimOk ? "432 x 648 pts confirmed" : "Unexpected interior page size" })
  checks.push({ name: "Title metadata", pass: subtitle.trim().length > 0, detail: subtitle || "MISSING" })
  const allPass = checks.every((c) => c.pass)
  const lines = [
    "ACCOUNTING BODY PRESS - KDP PRE-FLIGHT REPORT",
    "=============================================",
    "",
    "Book: " + subtitle + " (practice)",
    "Generated: " + new Date().toISOString(),
    "",
    ...checks.map((c) => (c.pass ? "[PASS] " : "[FAIL] ") + c.name + " - " + c.detail),
    "",
    allPass
      ? "VERDICT: KDP-READY - upload interior.pdf and cover.pdf as-is."
      : "VERDICT: NOT READY - resolve [FAIL] items before uploading to KDP.",
  ]
  return lines.join("\n")
}

function u32le(n: number): Buffer { const b = Buffer.alloc(4); b.writeUInt32LE(n, 0); return b }
function u16le(n: number): Buffer { const b = Buffer.alloc(2); b.writeUInt16LE(n, 0); return b }
function crc32(buf: Buffer): number {
  const t: number[] = []
  for (let i = 0; i < 256; i++) { let c = i; for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[i] = c }
  let crc = 0xffffffff
  for (let i = 0; i < buf.length; i++) crc = t[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8)
  return (crc ^ 0xffffffff) >>> 0
}
function buildZip(files: { name: string; data: Buffer }[]): Buffer {
  const locals: Buffer[] = []; const centrals: Buffer[] = []; let offset = 0
  for (const f of files) {
    const name = Buffer.from(f.name, "utf8"); const crc = crc32(f.data); const size = f.data.length
    const local = Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04]),u16le(20),u16le(0),u16le(0),u16le(0),u16le(0),u32le(crc),u32le(size),u32le(size),u16le(name.length),u16le(0),name,f.data])
    locals.push(local)
    centrals.push(Buffer.concat([Buffer.from([0x50,0x4b,0x01,0x02]),u16le(20),u16le(20),u16le(0),u16le(0),u16le(0),u16le(0),u32le(crc),u32le(size),u32le(size),u16le(name.length),u16le(0),u16le(0),u16le(0),u16le(0),u32le(0),u32le(offset),name]))
    offset += local.length
  }
  const cd = Buffer.concat(centrals)
  const eocd = Buffer.concat([Buffer.from([0x50,0x4b,0x05,0x06]),u16le(0),u16le(0),u16le(files.length),u16le(files.length),u32le(cd.length),u32le(offset),u16le(0)])
  return Buffer.concat([...locals, cd, eocd])
}

async function sha256Hex(message: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(message)
  const hashBuffer = await crypto.subtle.digest("SHA-256", msgBuffer)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("")
}

async function isAuthenticated(req: NextRequest): Promise<boolean> {
  const token = req.cookies.get("admin_token")?.value
  if (!token) return false
  const secret = process.env.ADMIN_SECRET
  if (!secret) return false
  const expectedHash = await sha256Hex(secret)
  return token === expectedHash
}

export async function POST(req: NextRequest) {
  if (!(await isAuthenticated(req))) {
    return NextResponse.json({ error: "Unauthorised" }, { status: 401 })
  }
  try {
    const body = await req.json()
    const { slug, edition, subtitle } = body
    if (!slug) return NextResponse.json({ error: "slug is required" }, { status: 400 })

    const fidelityStats = { mcqFailed: [] as string[], mcqNotFound: [] as string[] }
    const course = await buildCourse(slug, fidelityStats)

    const editionFinal  = edition  || "2026/27 Edition"
    const subtitleFinal = subtitle || course.title

    // Pass 1: structural probe — spacers only, no question/answer text —
    // fires onSectionPage with the real page number react-pdf lays each
    // section on.
    const sectionMap: Record<string, number> = {}
    await renderToBuffer(
      React.createElement(PracticeKitTemplate, {
        course,
        edition: editionFinal,
        subtitle: subtitleFinal,
        probeOnly: true,
        onSectionPage: (key: string, page: number) => { sectionMap[key] = page },
      }) as any
    )

    // Pass 2: full visual render, TOC page numbers filled from the probe map
    const interiorPdf = await renderToBuffer(
      React.createElement(PracticeKitTemplate, {
        course,
        edition: editionFinal,
        subtitle: subtitleFinal,
        pageMap: sectionMap,
      }) as any
    )

    const interiorStr = interiorPdf.toString("binary")
    const pageMatches = interiorStr.match(/\/Type\s*\/Page[^s]/g)
    const pageCount   = pageMatches ? pageMatches.length : 300

    const coverPdf = await renderToBuffer(
      React.createElement(FullCoverTemplate, {
        subtitle:  subtitleFinal,
        bookType:  "practice",
        edition:   editionFinal,
        pageCount,
      }) as any
    )

    const metaBuffer      = Buffer.from(buildMetadata(subtitleFinal, editionFinal, course), "utf8")
    const preflightBuffer = Buffer.from(buildPreflight(interiorPdf, coverPdf, pageCount, subtitleFinal) + "\n\n" + buildFidelity(course, fidelityStats), "utf8")

    const zip = buildZip([
      { name: "interior.pdf",         data: interiorPdf     },
      { name: "cover.pdf",            data: coverPdf        },
      { name: "metadata.txt",         data: metaBuffer      },
      { name: "preflight-report.txt", data: preflightBuffer },
    ])

    // ── Record publication state ─────────────────────────────────────────
    // Best-effort: the ZIP is already built, so a logging/DB failure here
    // must never fail the request - the admin still gets their download.
    try {
      const chapterCount = course.chapters.length
      let lessonCount = 0
      let articleCount = 0
      let questionCount = 0
      let articlesWithWebElements = 0
      let emptyArticles = 0

      for (const ch of course.chapters) {
        for (const ls of (ch.lessons || [])) {
          lessonCount++
          for (const art of (ls.linkedArticles || [])) {
            articleCount++
            questionCount += (art.quizQuestions || []).length
            const pubWarnings: string[] = (art.publicationWarnings || []).filter((w: string) => !w.startsWith("Total:"))
            if (pubWarnings.length > 0) articlesWithWebElements++
            const artBody = art.body || []
            const hasContent = artBody.some((b: any) => (b.children || []).some((c: any) => c.text?.trim()))
            if (!hasContent) emptyArticles++
          }
        }
      }

      const preflightStr    = preflightBuffer.toString()
      const kdpReady        = preflightStr.includes("VERDICT: KDP-READY")
      const preflightVerdict = preflightStr.split("\n").find((l) => l.startsWith("VERDICT:")) ?? ""
      const contentHash = await sha256Hex(
        course.slug + "|" + String(articleCount) + "|" + String(questionCount) + "|" + new Date().toISOString().slice(0, 19)
      )

      const sb = createSupabaseClient()
      const { error: insertError } = await sb.from("book_publications").insert({
        course_slug: course.slug,
        course_title: course.title,
        book_type: "practice",
        edition: editionFinal,
        subtitle: subtitleFinal,
        page_count: pageCount,
        chapter_count: chapterCount,
        lesson_count: lessonCount,
        article_count: articleCount,
        question_count: questionCount,
        kdp_ready: kdpReady,
        preflight_verdict: preflightVerdict,
        content_hash: contentHash,
        articles_with_web_elements: articlesWithWebElements,
        empty_articles: emptyArticles,
        platform: "ab",
      })
      if (insertError) {
        console.error("ab-press/generate-pq: book_publications insert failed:", insertError)
      }
    } catch (err) {
      console.error("ab-press/generate-pq: book_publications insert threw:", err)
    }

    return new NextResponse(new Uint8Array(zip), {
      status: 200,
      headers: {
        "Content-Type":        "application/zip",
        "Content-Disposition": `attachment; filename="${slug}-practice.zip"`,
        "Content-Length":      String(zip.length),
        "Cache-Control":       "no-store",
      },
    })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Unknown error"
    return NextResponse.json({ error: msg }, { status: 500 })
  }
}
